name: Len Villano
favicon: null
layout_spectrum: 0.25572723103687167
typography_spectrum: 0.7226863233372569
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8376599843613803
  lightness: 0.9649249245412648
  saturation: 0.738833752926439
  rhythmicContrast: 0.38057682453654706
purpose: []
